apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: poi
  name: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: poi
    spec:
      containers:
      - image: registrytvw4385.azurecr.io/tripinsights/poi:1.0
        name: poi
        env:
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tripinsightsecret
              key: SQL-PASSWORD
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: trip-config
        resources: {}
      volumes:
        - name: secrets-store-inline
          csi:
             driver: secrets-store.csi.k8s.io
             readOnly: true
             volumeAttributes:
               secretProviderClass: "azure-kvname"
             nodePublishSecretRef:                       # Only required when using service principal mode
               name: secrets-store-creds                 # Only required when using service principal mode
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: poi-service
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: poi
