apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: poi
  name: poi
spec:
  containers:
  - env:
    - name: SQL_USER
      value: sqladmintVw4385
    - name: SQL_PASSWORD
      value: aY9zn8Sh3
    - name: SQL_SERVER
      value: sqlservertvw4385.database.windows.net
    - name: ASPNETCORE_ENVIRONMENT
      value: Production
    - name: SQL_DBNAME
      value: mydrivingDB
    image: registrytvw4385.azurecr.io/tripinsights/poi:1.0
    name: poi
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
