apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-12-15T07:43:39Z"
  labels:
    run: tripviewer
  name: tripviewer
  namespace: default
spec:
  containers:
  - env:
    - name: USERPROFILE_API_ENDPOINT
      value: http://userprofile-service:80
    - name: TRIPS_API_ENDPOINT
      value: http://trips-service:80
    image: registrytvw4385.azurecr.io/tripviewer:latest
    imagePullPolicy: Always
    name: tripviewer
    ports:
    - containerPort: 80
