apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: trips
  name: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: trips
    spec:
      containers:
      - image: registrytvw4385.azurecr.io/tripinsights/trips:v1
        name: trips
        env:
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tripinsightsecret
              key: SQL-PASSWORD
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: trip-config
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: trips-service
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: trips
