apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tripinsight-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: poi-service
          servicePort: 80
        path: /api/poi/(.*)
        pathType: Prefix
      - backend:
          serviceName: trips-service
          servicePort: 80
        path: /api/trips/(.*)
        pathType: Prefix
      - backend:
          serviceName: userprofile-service
          servicePort: 80
        path: /api/user/(.*)
        pathType: Prefix
      - backend:
          serviceName: userjava-service
          servicePort: 80
        path: /api/user-java/(.*)
        pathType: Prefix
      - backend:
          serviceName: tripviewer-service
          servicePort: 80
        path: /(.*)
        pathType: Prefix
