apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tripviewer
  name: tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tripviewer
    spec:
      containers:
      - env:
        - name: USERPROFILE_API_ENDPOINT
          value: http://userprofile-service:80
        - name: TRIPS_API_ENDPOINT
          value: http://trips-service:80
        image: registrytvw4385.azurecr.io/tripviewer:latest
        name: tripviewer
        ports:
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: tripviewer
