apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: userprofile
  name: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: userprofile
    spec:
      containers:
      - image: registrytvw4385.azurecr.io/tripinsights/userprofile:latest
        name: userprofile
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: trip-config
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: userprofile

