apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: user-java
  name: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user-java
    spec:
      containers:
      - image: registrytvw4385.azurecr.io/tripinsights/user-java:1.0
        name: user-java
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: trip-config
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: userjava-service
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: user-java

